// <auto-generated />
using ClassRegistration.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassRegistration.Migrations
{
    [DbContext(typeof(ClassContext))]
    partial class ClassContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ClassRegistration.Models.GSUClass", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Credit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CourseId");

                    b.ToTable("GSUClasses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Capacity = 20,
                            Credit = 3,
                            Department = "Computer Science",
                            Name = "Advanced Operating System",
                            Number = "8735"
                        },
                        new
                        {
                            CourseId = 2,
                            Capacity = 20,
                            Credit = 3,
                            Department = "Computer Science",
                            Name = "Project Management for Information Technology",
                            Number = "8820"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
